services:
  proxy:
    image: nginx:stable
    ports:
      - "8443:443"
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./certs/
        target: /etc/nginx/certs
        read_only: true
