name: Test Goat
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYNT_ID: ${{ secrets.YOURPYNTID }}
      PYNT_APP_ID: d348bd9b-dff5-42c8-9fb3-34d3d6762ea9
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Setup and start the proxy
        run: |
          echo '127.0.0.1 proxy.goat.internal' | sudo tee -a /etc/hosts
          docker compose up -d
      - name: Verify the proxy is running with a custom CA
        run: curl --retry-all-errors --retry 3 -I --cacert certs/root.crt https://proxy.goat.internal:8443
      - name: Install pynt cli
        run: python3 -m pip install --upgrade pyntcli
      - name: Run the tests
        run: pynt command --captured-domains '*' --application-id $PYNT_APP_ID --host-ca certs/root.crt --ca-path certs/root-with-key.pem --cmd 'go test -v .'
